"""
GatherEase S3 Stack

Provisions:
  - S3 Bucket        for user-uploaded assets (avatars, recipe photos)
  - CORS policy      so Flutter web can upload directly via presigned POST
  - Lifecycle rules  move objects to cheaper storage tiers automatically
  - IAM policy doc   ready to attach to the ECS task role in Sprint 2
  - CfnOutputs       bucket name + ARN

Bucket structure (logical — not enforced by S3):
  avatars/{user_id}/profile.jpg
  gatherings/{gathering_id}/recipes/{dish_id}/{filename}

Objects are private by default. Access is granted exclusively through
presigned URLs generated by the FastAPI backend (app/services/s3.py).
"""

from __future__ import annotations

import aws_cdk as cdk
from aws_cdk import aws_iam as iam
from aws_cdk import aws_s3 as s3
from constructs import Construct


class GatherEaseS3Stack(cdk.Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        app_env: str,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        is_prod = app_env == "production"

        # ── Assets Bucket ─────────────────────────────────────────────────────
        self.assets_bucket = s3.Bucket(
            self,
            "GatherEaseAssets",
            bucket_name=f"gatherease-assets-{app_env}-{self.account}",

            # All objects private — access via presigned URLs only
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            public_read_access=False,

            # Encryption at rest (SSE-S3, no extra cost)
            encryption=s3.BucketEncryption.S3_MANAGED,

            # Versioning: on in prod (protects against accidental deletes),
            # off in dev (keeps costs minimal)
            versioned=is_prod,

            # CORS — allows Flutter web to upload directly via presigned POST
            cors=[
                s3.CorsRule(
                    allowed_methods=[
                        s3.HttpMethods.GET,
                        s3.HttpMethods.PUT,
                        s3.HttpMethods.POST,
                        s3.HttpMethods.HEAD,
                    ],
                    allowed_origins=["*"],   # tighten to your domain in prod
                    allowed_headers=["*"],
                    exposed_headers=[
                        "ETag",
                        "x-amz-server-side-encryption",
                        "x-amz-request-id",
                        "x-amz-id-2",
                    ],
                    max_age=3000,
                )
            ],

            # Lifecycle rules — move objects to cheaper tiers automatically
            lifecycle_rules=[
                # Avatars: keep current version in STANDARD, move old versions to IA
                s3.LifecycleRule(
                    id="avatars-old-versions",
                    prefix="avatars/",
                    noncurrent_version_transitions=[
                        s3.NoncurrentVersionTransition(
                            storage_class=s3.StorageClass.INFREQUENT_ACCESS,
                            transition_after=cdk.Duration.days(30),
                        )
                    ],
                    noncurrent_version_expiration=cdk.Duration.days(90),
                    enabled=is_prod,
                ),
                # Recipe photos: transition to STANDARD_IA after 60 days
                s3.LifecycleRule(
                    id="recipe-photos-ia",
                    prefix="gatherings/",
                    transitions=[
                        s3.Transition(
                            storage_class=s3.StorageClass.INFREQUENT_ACCESS,
                            transition_after=cdk.Duration.days(60),
                        )
                    ],
                    enabled=True,
                ),
                # Abort incomplete multipart uploads after 7 days
                s3.LifecycleRule(
                    id="abort-incomplete-multipart",
                    abort_incomplete_multipart_upload_after=cdk.Duration.days(7),
                    enabled=True,
                ),
            ],

            # Access logging (prod only — extra cost in dev)
            server_access_logs_prefix="access-logs/" if is_prod else None,

            removal_policy=(
                cdk.RemovalPolicy.RETAIN if is_prod else cdk.RemovalPolicy.DESTROY
            ),
            auto_delete_objects=not is_prod,  # only safe in dev
        )

        # ── IAM Policy Document ───────────────────────────────────────────────
        # Attach this to the ECS task role in Sprint 2.
        # Exported as a managed policy so the ECS stack can import it by name.
        self.s3_access_policy = iam.ManagedPolicy(
            self,
            "S3AccessPolicy",
            managed_policy_name=f"GatherEase-S3Access-{app_env}",
            description="Allows GatherEase ECS tasks to read/write the assets bucket",
            statements=[
                iam.PolicyStatement(
                    sid="ListBucket",
                    effect=iam.Effect.ALLOW,
                    actions=["s3:ListBucket"],
                    resources=[self.assets_bucket.bucket_arn],
                ),
                iam.PolicyStatement(
                    sid="ReadWriteObjects",
                    effect=iam.Effect.ALLOW,
                    actions=[
                        "s3:GetObject",
                        "s3:PutObject",
                        "s3:DeleteObject",
                        "s3:GetObjectVersion",
                    ],
                    resources=[f"{self.assets_bucket.bucket_arn}/*"],
                ),
                iam.PolicyStatement(
                    sid="GeneratePresignedUrls",
                    effect=iam.Effect.ALLOW,
                    actions=["s3:PutObject"],   # required for presigned POST
                    resources=[f"{self.assets_bucket.bucket_arn}/avatars/*",
                                f"{self.assets_bucket.bucket_arn}/gatherings/*"],
                ),
            ],
        )

        # ── Outputs ───────────────────────────────────────────────────────────

        cdk.CfnOutput(
            self,
            "BucketName",
            value=self.assets_bucket.bucket_name,
            description="S3_BUCKET_NAME — copy into your .env",
            export_name=f"GatherEase-{app_env}-BucketName",
        )
        cdk.CfnOutput(
            self,
            "BucketArn",
            value=self.assets_bucket.bucket_arn,
            description="S3 bucket ARN",
            export_name=f"GatherEase-{app_env}-BucketArn",
        )
        cdk.CfnOutput(
            self,
            "S3AccessPolicyArn",
            value=self.s3_access_policy.managed_policy_arn,
            description="Attach this managed policy to the ECS task role in Sprint 2",
            export_name=f"GatherEase-{app_env}-S3AccessPolicyArn",
        )
        cdk.CfnOutput(
            self,
            "BucketRegion",
            value=self.region,
            description="AWS_REGION for S3 client",
        )
